### ISSUE TITLE
Veritechs Do not have any Texture Files

### ISSUE THREAD

**Issue by salcor3052** [ScornMandark/gundam-tts-assets#3]
Hello, I was looking through you unity3d files for your TTS package and I noticed that none of you Veritech models have the associated texture files with them.  Is this why the mod won't upload the macross files in TTS?

**Comment by MarkBell1701C** [comment]
I'm not finding the problem with the veritechs - none of the unity3d files have a separate texture file, since they're embedded.  Can you tell me more about the problem?  Have you tried force refreshing the mod?  There's a "Reinitialize" option in the settings menu that should redownload the main file, since you may be operating from a cached copy.

![image](https://user-images.githubusercontent.com/62667199/177904465-7f781677-3d20-41b3-9600-db0fd26bd395.png)

**Comment by ScornMandark** [comment]
None of the mod files have a separate texture to load, since they're embedded in the .unity3d asset bundle.  Can you tell me more about the problem?  Have you tried Reinitializing through the settings menu?  If you're operating on a cached copy, it may not load correctly, and reinitializing should force it to redownload the main file.

![image](https://user-images.githubusercontent.com/7913700/177904806-e627265c-4a69-4a31-af42-35f02a45a9e0.png)

**Comment by salcor3052** [comment]
Gotcha. I got it working today thank you.

**Comment by ScornMandark** [comment]
Great! Glad to hear it :) I'll mark this one closed then

**Comment by salcor3052** [comment]
I would like to ask an expanded question.  I am trying to find some good Veritech models to import into the Talespire virtual tabletop to play Robotech RPGs.  Your models are the main ones that I have found.  I am looking at the veritech unity3d files through asset studio but I do not see any textures for the various models.  Would you have the various textures and be willing to share them?
Salcor    On Friday, July 8, 2022 at 11:29:18 PM CDT, ScornMandark ***@***.***> wrote:  
 
 


Great! Glad to hear it :) I'll mark this one closed then
